---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Install dnsutils so dig can be used
    apt:
      name: dnsutils
      state: present
    become: true

  - name: Get DNS record of fritz.box from single_hosts
    command: "dig +noall +answer fritz.box"
    register: dig_result
    changed_when: false
  - name: Assert that the IP for fritz.box is correct
    assert:
      that:
        - dig_result.stdout is search( 'fritz.box' )
        - dig_result.stdout is search( '192.168.178.1' )

  - name: Get DNS record of server2.home.example.com from local_domains
    command: "dig +noall +answer server2.home.example.com"
    register: dig_result
    changed_when: false
  - name: Assert that the IP for server2.home.example.com is correct
    assert:
      that:
        - dig_result.stdout is search( 'server2.home.example.com' )
        - dig_result.stdout is search( '192.168.2.102' )

  - name: Get DNS record of clusternode4.homelab.local from local_domains
    command: "dig +noall +answer clusternode4.homelab.local"
    register: dig_result
    changed_when: false
  - name: Assert that the IP for clusternode4.homelab.local is correct
    assert:
      that:
        - dig_result.stdout is search( 'clusternode4.homelab.local' )
        - dig_result.stdout is search( '192.168.2.114' )
