---
name: 'CI'
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:

  test:
    name: Molecule tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install test dependencies
        run: pip3 install ansible yamllint ansible-lint
      - name: Show current dir
        run: echo $PWD
      - name: Lint with yamllint
        run: yamllint .
      - name: Move playbook to correct folder
        run: mv tests/* ../
      - name: Lint with ansible-lint
        run: yamllint .
      - name: Overwrite local resolv.conf
        run: echo 'nameserver 127.0.0.1' | cat - /etc/resolv.conf > temp && sudo mv temp /etc/resolv.conf
      - name: Run tests
        run: molecule test --scenario-name ${{ matrix.distro }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLORS: "1"
