---
name: 'CI'
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:

  test:
    name: Molecule tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install test dependencies
        run: pip3 install ansible yamllint ansible-lint
      - name: Lint with yamllint
        run: yamllint .
      - name: Create correct directory structure for test
        run: |
          mkdir roles
          mkdir roles/dnsmasq
          ls | grep -v roles | xargs -i mv {} roles/dnsmasq
          mv roles/dnsmasq/tests/* .
      - name: Lint with ansible-lint
        run: ansible-lint test.yml
      - name: Run tests
        run: ansible-playbook test.yml
      -run: journalctl -xe
